package com.comiteetica.hibernate.model;
// Generated 04-ago-2017 18:25:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorrespondenciaFileId generated by hbm2java
 */
@Embeddable
public class CorrespondenciaFileId  implements java.io.Serializable {


     private String idCorrespondencia;
     private int fileDetalle;

    public CorrespondenciaFileId() {
    }

    public CorrespondenciaFileId(String idCorrespondencia, int fileDetalle) {
       this.idCorrespondencia = idCorrespondencia;
       this.fileDetalle = fileDetalle;
    }
   


    @Column(name="IdCorrespondencia", nullable=false, length=10)
    public String getIdCorrespondencia() {
        return this.idCorrespondencia;
    }
    
    public void setIdCorrespondencia(String idCorrespondencia) {
        this.idCorrespondencia = idCorrespondencia;
    }


    @Column(name="FileDetalle", nullable=false)
    public int getFileDetalle() {
        return this.fileDetalle;
    }
    
    public void setFileDetalle(int fileDetalle) {
        this.fileDetalle = fileDetalle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CorrespondenciaFileId) ) return false;
		 CorrespondenciaFileId castOther = ( CorrespondenciaFileId ) other; 
         
		 return ( (this.getIdCorrespondencia()==castOther.getIdCorrespondencia()) || ( this.getIdCorrespondencia()!=null && castOther.getIdCorrespondencia()!=null && this.getIdCorrespondencia().equals(castOther.getIdCorrespondencia()) ) )
 && (this.getFileDetalle()==castOther.getFileDetalle());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCorrespondencia() == null ? 0 : this.getIdCorrespondencia().hashCode() );
         result = 37 * result + this.getFileDetalle();
         return result;
   }   


}


