package com.comiteetica.hibernate.model;
// Generated 11-ago-2017 18:56:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorrespondenciaServicioId generated by hbm2java
 */
@Embeddable
public class CorrespondenciaServicioId  implements java.io.Serializable {


     private String idCorrespondencia;
     private int idCorrespondenciaServicio;

    public CorrespondenciaServicioId() {
    }

    public CorrespondenciaServicioId(String idCorrespondencia, int idCorrespondenciaServicio) {
       this.idCorrespondencia = idCorrespondencia;
       this.idCorrespondenciaServicio = idCorrespondenciaServicio;
    }
   


    @Column(name="IdCorrespondencia", nullable=false, length=10)
    public String getIdCorrespondencia() {
        return this.idCorrespondencia;
    }
    
    public void setIdCorrespondencia(String idCorrespondencia) {
        this.idCorrespondencia = idCorrespondencia;
    }


    @Column(name="IdCorrespondenciaServicio", nullable=false)
    public int getIdCorrespondenciaServicio() {
        return this.idCorrespondenciaServicio;
    }
    
    public void setIdCorrespondenciaServicio(int idCorrespondenciaServicio) {
        this.idCorrespondenciaServicio = idCorrespondenciaServicio;
    }




}


