package com.comiteetica.hibernate.model;
// Generated 09-ago-2017 12:35:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorrespondenciaFileId generated by hbm2java
 */
@Embeddable
public class CorrespondenciaFileId  implements java.io.Serializable {


     private String idCorrespondencia;
     private int fileDetalle;

    public CorrespondenciaFileId() {
    }

    public CorrespondenciaFileId(String idCorrespondencia, int fileDetalle) {
       this.idCorrespondencia = idCorrespondencia;
       this.fileDetalle = fileDetalle;
    }
   


    @Column(name="IdCorrespondencia", nullable=false, length=10)
    public String getIdCorrespondencia() {
        return this.idCorrespondencia;
    }
    
    public void setIdCorrespondencia(String idCorrespondencia) {
        this.idCorrespondencia = idCorrespondencia;
    }


    @Column(name="FileDetalle", nullable=false)
    public int getFileDetalle() {
        return this.fileDetalle;
    }
    
    public void setFileDetalle(int fileDetalle) {
        this.fileDetalle = fileDetalle;
    }




}


