package com.comiteetica.hibernate.model;
// Generated 04-ago-2017 18:25:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorrespondenciaServicioId generated by hbm2java
 */
@Embeddable
public class CorrespondenciaServicioId  implements java.io.Serializable {


     private String idCorrespondencia;
     private int idCorrespondenciaServicio;

    public CorrespondenciaServicioId() {
    }

    public CorrespondenciaServicioId(String idCorrespondencia, int idCorrespondenciaServicio) {
       this.idCorrespondencia = idCorrespondencia;
       this.idCorrespondenciaServicio = idCorrespondenciaServicio;
    }
   


    @Column(name="IdCorrespondencia", nullable=false, length=10)
    public String getIdCorrespondencia() {
        return this.idCorrespondencia;
    }
    
    public void setIdCorrespondencia(String idCorrespondencia) {
        this.idCorrespondencia = idCorrespondencia;
    }


    @Column(name="IdCorrespondenciaServicio", nullable=false)
    public int getIdCorrespondenciaServicio() {
        return this.idCorrespondenciaServicio;
    }
    
    public void setIdCorrespondenciaServicio(int idCorrespondenciaServicio) {
        this.idCorrespondenciaServicio = idCorrespondenciaServicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CorrespondenciaServicioId) ) return false;
		 CorrespondenciaServicioId castOther = ( CorrespondenciaServicioId ) other; 
         
		 return ( (this.getIdCorrespondencia()==castOther.getIdCorrespondencia()) || ( this.getIdCorrespondencia()!=null && castOther.getIdCorrespondencia()!=null && this.getIdCorrespondencia().equals(castOther.getIdCorrespondencia()) ) )
 && (this.getIdCorrespondenciaServicio()==castOther.getIdCorrespondenciaServicio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCorrespondencia() == null ? 0 : this.getIdCorrespondencia().hashCode() );
         result = 37 * result + this.getIdCorrespondenciaServicio();
         return result;
   }   


}


