package com.comiteetica.hibernate.model;
// Generated 16/06/2017 12:59:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name="Distrito"
    ,schema="dbo"
    ,catalog="ComiteEtica"
)
public class Distrito  implements java.io.Serializable {


     private DistritoId id;
     private Provincia provincia;
     private String descripcion;
     private String usuarioIngresa;
     private Date fechaIngreso;
     private String usuarioModifica;
     private Date fechaModificacion;
     private Set<Sede> sedes = new HashSet<Sede>(0);

    public Distrito() {
    }

	
    public Distrito(DistritoId id, Provincia provincia) {
        this.id = id;
        this.provincia = provincia;
    }
    public Distrito(DistritoId id, Provincia provincia, String descripcion, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion, Set<Sede> sedes) {
       this.id = id;
       this.provincia = provincia;
       this.descripcion = descripcion;
       this.usuarioIngresa = usuarioIngresa;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModifica = usuarioModifica;
       this.fechaModificacion = fechaModificacion;
       this.sedes = sedes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idDepartamento", column=@Column(name="IdDepartamento", nullable=false, length=2) ), 
        @AttributeOverride(name="idProvincia", column=@Column(name="IdProvincia", nullable=false, length=2) ), 
        @AttributeOverride(name="idDistrito", column=@Column(name="IdDistrito", nullable=false, length=2) ) } )
    public DistritoId getId() {
        return this.id;
    }
    
    public void setId(DistritoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IdDepartamento", referencedColumnName="IdDepartamento", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IdProvincia", referencedColumnName="IdProvincia", nullable=false, insertable=false, updatable=false) } )
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="Descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="UsuarioIngresa", length=50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }
    
    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaIngreso", length=23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="UsuarioModifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaModificacion", length=23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="distrito")
    public Set<Sede> getSedes() {
        return this.sedes;
    }
    
    public void setSedes(Set<Sede> sedes) {
        this.sedes = sedes;
    }




}


