package com.comiteetica.hibernate.model;
// Generated 09-ago-2017 12:35:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DistritoId generated by hbm2java
 */
@Embeddable
public class DistritoId  implements java.io.Serializable {


     private String idDepartamento;
     private String idProvincia;
     private String idDistrito;

    public DistritoId() {
    }

    public DistritoId(String idDepartamento, String idProvincia, String idDistrito) {
       this.idDepartamento = idDepartamento;
       this.idProvincia = idProvincia;
       this.idDistrito = idDistrito;
    }
   


    @Column(name="IdDepartamento", nullable=false, length=2)
    public String getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(String idDepartamento) {
        this.idDepartamento = idDepartamento;
    }


    @Column(name="IdProvincia", nullable=false, length=2)
    public String getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(String idProvincia) {
        this.idProvincia = idProvincia;
    }


    @Column(name="IdDistrito", nullable=false, length=2)
    public String getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(String idDistrito) {
        this.idDistrito = idDistrito;
    }




}


