package com.comiteetica.hibernate.model;
// Generated 11-ago-2017 18:56:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FechaSesion generated by hbm2java
 */
@Entity
@Table(name="FechaSesion"
    ,schema="dbo"
    ,catalog="ComiteEtica"
)
public class FechaSesion  implements java.io.Serializable {


     private int idFechaSesion;
     private Date fechaSesion;
     private String observacion;
     private String usuarioIngresa;
     private Date fechaIngreso;
     private String usuarioModifica;
     private Date fechaModificacion;

    public FechaSesion() {
    }

	
    public FechaSesion(int idFechaSesion) {
        this.idFechaSesion = idFechaSesion;
    }
    public FechaSesion(int idFechaSesion, Date fechaSesion, String observacion, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion) {
       this.idFechaSesion = idFechaSesion;
       this.fechaSesion = fechaSesion;
       this.observacion = observacion;
       this.usuarioIngresa = usuarioIngresa;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModifica = usuarioModifica;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="IdFechaSesion", nullable=false)
    public int getIdFechaSesion() {
        return this.idFechaSesion;
    }
    
    public void setIdFechaSesion(int idFechaSesion) {
        this.idFechaSesion = idFechaSesion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaSesion", length=23)
    public Date getFechaSesion() {
        return this.fechaSesion;
    }
    
    public void setFechaSesion(Date fechaSesion) {
        this.fechaSesion = fechaSesion;
    }

    
    @Column(name="Observacion", length=500)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="UsuarioIngresa", length=50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }
    
    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaIngreso", length=23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="UsuarioModifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaModificacion", length=23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


