package com.comiteetica.hibernate.model;
// Generated 11-sep-2017 10:52:48 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formato generated by hbm2java
 */
@Entity
@Table(name = "Formato",
         schema = "dbo",
         catalog = "ComiteEtica"
)
public class Formato implements java.io.Serializable {

    private int idFormato;
    private String descripcion;
    private String usuarioIngresa;
    private Date fechaIngreso;
    private String usuarioModifica;
    private Date fechaModificacion;
    @JsonManagedReference
    private Set<FormatoLinea> formatoLineas = new HashSet<FormatoLinea>(0);

    public Formato() {
    }

    public Formato(int idFormato) {
        this.idFormato = idFormato;
    }

    public Formato(int idFormato, String descripcion, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion, Set<FormatoLinea> formatoLineas) {
        this.idFormato = idFormato;
        this.descripcion = descripcion;
        this.usuarioIngresa = usuarioIngresa;
        this.fechaIngreso = fechaIngreso;
        this.usuarioModifica = usuarioModifica;
        this.fechaModificacion = fechaModificacion;
        this.formatoLineas = formatoLineas;
    }

    @Id

    @Column(name = "IdFormato", unique = true, nullable = false)
    public int getIdFormato() {
        return this.idFormato;
    }

    public void setIdFormato(int idFormato) {
        this.idFormato = idFormato;
    }

    @Column(name = "Descripcion", length = 150)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "UsuarioIngresa", length = 50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }

    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaIngreso", length = 23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    @Column(name = "UsuarioModifica", length = 50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaModificacion", length = 23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "formato")
    public Set<FormatoLinea> getFormatoLineas() {
        return this.formatoLineas;
    }

    public void setFormatoLineas(Set<FormatoLinea> formatoLineas) {
        this.formatoLineas = formatoLineas;
    }

}
