package com.comiteetica.hibernate.model;
// Generated 11-sep-2017 10:52:48 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormatoLinea generated by hbm2java
 */
@Entity
@Table(name = "FormatoLinea",
         schema = "dbo",
         catalog = "ComiteEtica"
)
public class FormatoLinea implements java.io.Serializable {

    private FormatoLineaId id;
    @JsonBackReference
    private Formato formato;
    private String contenido;
    private String estilo;
    private String alineacion;
    private String color;
    private String usuarioIngresa;
    private Date fechaIngreso;
    private String usuarioModifica;
    private Date fechaModificacion;

    public FormatoLinea() {
    }

    public FormatoLinea(FormatoLineaId id, Formato formato) {
        this.id = id;
        this.formato = formato;
    }

    public FormatoLinea(FormatoLineaId id, Formato formato, String contenido, String estilo, String alineacion, String color, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion) {
        this.id = id;
        this.formato = formato;
        this.contenido = contenido;
        this.estilo = estilo;
        this.alineacion = alineacion;
        this.color = color;
        this.usuarioIngresa = usuarioIngresa;
        this.fechaIngreso = fechaIngreso;
        this.usuarioModifica = usuarioModifica;
        this.fechaModificacion = fechaModificacion;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idFormato", column = @Column(name = "IdFormato", nullable = false))
        , 
        @AttributeOverride(name = "idFormatoLinea", column = @Column(name = "IdFormatoLinea", nullable = false))})
    public FormatoLineaId getId() {
        return this.id;
    }

    public void setId(FormatoLineaId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdFormato", nullable = false, insertable = false, updatable = false)
    public Formato getFormato() {
        return this.formato;
    }

    public void setFormato(Formato formato) {
        this.formato = formato;
    }

    @Column(name = "Contenido")
    public String getContenido() {
        return this.contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    @Column(name = "Estilo", length = 500)
    public String getEstilo() {
        return this.estilo;
    }

    public void setEstilo(String estilo) {
        this.estilo = estilo;
    }

    @Column(name = "Alineacion", length = 500)
    public String getAlineacion() {
        return this.alineacion;
    }

    public void setAlineacion(String alineacion) {
        this.alineacion = alineacion;
    }

    @Column(name = "Color", length = 500)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    @Column(name = "UsuarioIngresa", length = 50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }

    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaIngreso", length = 23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    @Column(name = "UsuarioModifica", length = 50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaModificacion", length = 23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

}
