package com.comiteetica.hibernate.model;
// Generated 11-ago-2017 18:56:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigacionMonitorId generated by hbm2java
 */
@Embeddable
public class InvestigacionMonitorId  implements java.io.Serializable {


     private String idInvestigacion;
     private String idMonitor;

    public InvestigacionMonitorId() {
    }

    public InvestigacionMonitorId(String idInvestigacion, String idMonitor) {
       this.idInvestigacion = idInvestigacion;
       this.idMonitor = idMonitor;
    }
   


    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }


    @Column(name="IdMonitor", nullable=false, length=10)
    public String getIdMonitor() {
        return this.idMonitor;
    }
    
    public void setIdMonitor(String idMonitor) {
        this.idMonitor = idMonitor;
    }




}


