package com.comiteetica.hibernate.model;
// Generated 17-jun-2017 14:55:19 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Investigacion generated by hbm2java
 */
@Entity
@Table(name="Investigacion"
    ,schema="dbo"
    ,catalog="ComiteEtica"
)
public class Investigacion  implements java.io.Serializable {


     private String idInvestigacion;
     private PatrocinadorCro patrocinadorCro;
     private String protocolo;
     private String titulo;
     private String paramEspecialidad;
     private String paramFase;
     private String paramTipoInvestigacion;
     private String usuarioIngresa;
     private Date fechaIngreso;
     private String usuarioModifica;
     private Date fechaModificacion;
     private Set<InvestigacionMonitor> investigacionMonitors = new HashSet<InvestigacionMonitor>(0);
     
     @JsonManagedReference("InvestigacionCoordinador")
     private Set<InvestigacionCoordinador> investigacionCoordinadors = new HashSet<InvestigacionCoordinador>(0);
     
     private Set<InvestigacionInvestigador> investigacionInvestigadors = new HashSet<InvestigacionInvestigador>(0);
     private Set<Registro> registros = new HashSet<Registro>(0);
     private Set<InvestigacionSede> investigacionSedes = new HashSet<InvestigacionSede>(0);

    public Investigacion() {
    }

	
    public Investigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }
    public Investigacion(String idInvestigacion, PatrocinadorCro patrocinadorCro, String protocolo, String titulo, String paramEspecialidad, String paramFase, String paramTipoInvestigacion, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion, Set<InvestigacionMonitor> investigacionMonitors, Set<InvestigacionCoordinador> investigacionCoordinadors, Set<InvestigacionInvestigador> investigacionInvestigadors, Set<Registro> registros, Set<InvestigacionSede> investigacionSedes) {
       this.idInvestigacion = idInvestigacion;
       this.patrocinadorCro = patrocinadorCro;
       this.protocolo = protocolo;
       this.titulo = titulo;
       this.paramEspecialidad = paramEspecialidad;
       this.paramFase = paramFase;
       this.paramTipoInvestigacion = paramTipoInvestigacion;
       this.usuarioIngresa = usuarioIngresa;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModifica = usuarioModifica;
       this.fechaModificacion = fechaModificacion;
       this.investigacionMonitors = investigacionMonitors;
       this.investigacionCoordinadors = investigacionCoordinadors;
       this.investigacionInvestigadors = investigacionInvestigadors;
       this.registros = registros;
       this.investigacionSedes = investigacionSedes;
    }
   
     @Id 

    
    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IdPatrocinador", referencedColumnName="IdPatrocinador"), 
        @JoinColumn(name="IdCro", referencedColumnName="IdCro") } )
    public PatrocinadorCro getPatrocinadorCro() {
        return this.patrocinadorCro;
    }
    
    public void setPatrocinadorCro(PatrocinadorCro patrocinadorCro) {
        this.patrocinadorCro = patrocinadorCro;
    }

    
    @Column(name="Protocolo", length=150)
    public String getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(String protocolo) {
        this.protocolo = protocolo;
    }

    
    @Column(name="Titulo", length=1000)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="ParamEspecialidad", length=4)
    public String getParamEspecialidad() {
        return this.paramEspecialidad;
    }
    
    public void setParamEspecialidad(String paramEspecialidad) {
        this.paramEspecialidad = paramEspecialidad;
    }

    
    @Column(name="ParamFase", length=4)
    public String getParamFase() {
        return this.paramFase;
    }
    
    public void setParamFase(String paramFase) {
        this.paramFase = paramFase;
    }

    
    @Column(name="ParamTipoInvestigacion", length=4)
    public String getParamTipoInvestigacion() {
        return this.paramTipoInvestigacion;
    }
    
    public void setParamTipoInvestigacion(String paramTipoInvestigacion) {
        this.paramTipoInvestigacion = paramTipoInvestigacion;
    }

    
    @Column(name="UsuarioIngresa", length=50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }
    
    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaIngreso", length=23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="UsuarioModifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaModificacion", length=23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investigacion")
    public Set<InvestigacionMonitor> getInvestigacionMonitors() {
        return this.investigacionMonitors;
    }
    
    public void setInvestigacionMonitors(Set<InvestigacionMonitor> investigacionMonitors) {
        this.investigacionMonitors = investigacionMonitors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investigacion")
    public Set<InvestigacionCoordinador> getInvestigacionCoordinadors() {
        return this.investigacionCoordinadors;
    }
    
    public void setInvestigacionCoordinadors(Set<InvestigacionCoordinador> investigacionCoordinadors) {
        this.investigacionCoordinadors = investigacionCoordinadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investigacion")
    public Set<InvestigacionInvestigador> getInvestigacionInvestigadors() {
        return this.investigacionInvestigadors;
    }
    
    public void setInvestigacionInvestigadors(Set<InvestigacionInvestigador> investigacionInvestigadors) {
        this.investigacionInvestigadors = investigacionInvestigadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investigacion")
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investigacion")
    public Set<InvestigacionSede> getInvestigacionSedes() {
        return this.investigacionSedes;
    }
    
    public void setInvestigacionSedes(Set<InvestigacionSede> investigacionSedes) {
        this.investigacionSedes = investigacionSedes;
    }




}


