package com.comiteetica.hibernate.model;
// Generated 17-jun-2017 14:55:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvestigacionMonitor generated by hbm2java
 */
@Entity
@Table(name="InvestigacionMonitor"
    ,schema="dbo"
    ,catalog="ComiteEtica"
)
public class InvestigacionMonitor  implements java.io.Serializable {


     private InvestigacionMonitorId id;
     private Investigacion investigacion;
     private Monitor monitor;
     private String observacion;
     private String usuarioIngresa;
     private Date fechaIngreso;
     private String usuarioModifica;
     private Date fechaModificacion;

    public InvestigacionMonitor() {
    }

	
    public InvestigacionMonitor(InvestigacionMonitorId id, Investigacion investigacion, Monitor monitor) {
        this.id = id;
        this.investigacion = investigacion;
        this.monitor = monitor;
    }
    public InvestigacionMonitor(InvestigacionMonitorId id, Investigacion investigacion, Monitor monitor, String observacion, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion) {
       this.id = id;
       this.investigacion = investigacion;
       this.monitor = monitor;
       this.observacion = observacion;
       this.usuarioIngresa = usuarioIngresa;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModifica = usuarioModifica;
       this.fechaModificacion = fechaModificacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idInvestigacion", column=@Column(name="IdInvestigacion", nullable=false, length=10) ), 
        @AttributeOverride(name="idMonitor", column=@Column(name="IdMonitor", nullable=false, length=10) ) } )
    public InvestigacionMonitorId getId() {
        return this.id;
    }
    
    public void setId(InvestigacionMonitorId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdInvestigacion", nullable=false, insertable=false, updatable=false)
    public Investigacion getInvestigacion() {
        return this.investigacion;
    }
    
    public void setInvestigacion(Investigacion investigacion) {
        this.investigacion = investigacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdMonitor", nullable=false, insertable=false, updatable=false)
    public Monitor getMonitor() {
        return this.monitor;
    }
    
    public void setMonitor(Monitor monitor) {
        this.monitor = monitor;
    }

    
    @Column(name="Observacion", length=250)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="UsuarioIngresa", length=50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }
    
    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaIngreso", length=23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="UsuarioModifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaModificacion", length=23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


