package com.comiteetica.hibernate.model;
// Generated 16/06/2017 12:59:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigacionMonitorId generated by hbm2java
 */
@Embeddable
public class InvestigacionMonitorId  implements java.io.Serializable {


     private String idInvestigacion;
     private String idMonitor;

    public InvestigacionMonitorId() {
    }

    public InvestigacionMonitorId(String idInvestigacion, String idMonitor) {
       this.idInvestigacion = idInvestigacion;
       this.idMonitor = idMonitor;
    }
   


    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }


    @Column(name="IdMonitor", nullable=false, length=10)
    public String getIdMonitor() {
        return this.idMonitor;
    }
    
    public void setIdMonitor(String idMonitor) {
        this.idMonitor = idMonitor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvestigacionMonitorId) ) return false;
		 InvestigacionMonitorId castOther = ( InvestigacionMonitorId ) other; 
         
		 return ( (this.getIdInvestigacion()==castOther.getIdInvestigacion()) || ( this.getIdInvestigacion()!=null && castOther.getIdInvestigacion()!=null && this.getIdInvestigacion().equals(castOther.getIdInvestigacion()) ) )
 && ( (this.getIdMonitor()==castOther.getIdMonitor()) || ( this.getIdMonitor()!=null && castOther.getIdMonitor()!=null && this.getIdMonitor().equals(castOther.getIdMonitor()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdInvestigacion() == null ? 0 : this.getIdInvestigacion().hashCode() );
         result = 37 * result + ( getIdMonitor() == null ? 0 : this.getIdMonitor().hashCode() );
         return result;
   }   


}


