package com.comiteetica.hibernate.model;
// Generated 04-ago-2017 18:25:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigacionSedeId generated by hbm2java
 */
@Embeddable
public class InvestigacionSedeId  implements java.io.Serializable {


     private String idInvestigacion;
     private String idSede;

    public InvestigacionSedeId() {
    }

    public InvestigacionSedeId(String idInvestigacion, String idSede) {
       this.idInvestigacion = idInvestigacion;
       this.idSede = idSede;
    }
   


    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }


    @Column(name="IdSede", nullable=false, length=10)
    public String getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(String idSede) {
        this.idSede = idSede;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvestigacionSedeId) ) return false;
		 InvestigacionSedeId castOther = ( InvestigacionSedeId ) other; 
         
		 return ( (this.getIdInvestigacion()==castOther.getIdInvestigacion()) || ( this.getIdInvestigacion()!=null && castOther.getIdInvestigacion()!=null && this.getIdInvestigacion().equals(castOther.getIdInvestigacion()) ) )
 && ( (this.getIdSede()==castOther.getIdSede()) || ( this.getIdSede()!=null && castOther.getIdSede()!=null && this.getIdSede().equals(castOther.getIdSede()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdInvestigacion() == null ? 0 : this.getIdInvestigacion().hashCode() );
         result = 37 * result + ( getIdSede() == null ? 0 : this.getIdSede().hashCode() );
         return result;
   }   


}


