package com.comiteetica.hibernate.model;
// Generated 17-jun-2017 14:55:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigacionSedeId generated by hbm2java
 */
@Embeddable
public class InvestigacionSedeId  implements java.io.Serializable {


     private String idInvestigacion;
     private String idSede;

    public InvestigacionSedeId() {
    }

    public InvestigacionSedeId(String idInvestigacion, String idSede) {
       this.idInvestigacion = idInvestigacion;
       this.idSede = idSede;
    }
   


    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }


    @Column(name="IdSede", nullable=false, length=10)
    public String getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(String idSede) {
        this.idSede = idSede;
    }




}


