package com.comiteetica.hibernate.model;
// Generated 09-ago-2017 12:35:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigacionInvestigadorId generated by hbm2java
 */
@Embeddable
public class InvestigacionInvestigadorId  implements java.io.Serializable {


     private String idInvestigacion;
     private String idInvestigador;

    public InvestigacionInvestigadorId() {
    }

    public InvestigacionInvestigadorId(String idInvestigacion, String idInvestigador) {
       this.idInvestigacion = idInvestigacion;
       this.idInvestigador = idInvestigador;
    }
   


    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }


    @Column(name="IdInvestigador", nullable=false, length=10)
    public String getIdInvestigador() {
        return this.idInvestigador;
    }
    
    public void setIdInvestigador(String idInvestigador) {
        this.idInvestigador = idInvestigador;
    }




}


