package com.comiteetica.hibernate.model;
// Generated 09-ago-2017 12:35:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigacionCoordinadorId generated by hbm2java
 */
@Embeddable
public class InvestigacionCoordinadorId  implements java.io.Serializable {


     private String idInvestigacion;
     private String idCoordinador;

    public InvestigacionCoordinadorId() {
    }

    public InvestigacionCoordinadorId(String idInvestigacion, String idCoordinador) {
       this.idInvestigacion = idInvestigacion;
       this.idCoordinador = idCoordinador;
    }
   


    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }


    @Column(name="IdCoordinador", nullable=false, length=10)
    public String getIdCoordinador() {
        return this.idCoordinador;
    }
    
    public void setIdCoordinador(String idCoordinador) {
        this.idCoordinador = idCoordinador;
    }




}


