package com.comiteetica.hibernate.model;
// Generated 04-ago-2017 18:25:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvestigacionInvestigadorId generated by hbm2java
 */
@Embeddable
public class InvestigacionInvestigadorId  implements java.io.Serializable {


     private String idInvestigacion;
     private String idInvestigador;

    public InvestigacionInvestigadorId() {
    }

    public InvestigacionInvestigadorId(String idInvestigacion, String idInvestigador) {
       this.idInvestigacion = idInvestigacion;
       this.idInvestigador = idInvestigador;
    }
   


    @Column(name="IdInvestigacion", nullable=false, length=10)
    public String getIdInvestigacion() {
        return this.idInvestigacion;
    }
    
    public void setIdInvestigacion(String idInvestigacion) {
        this.idInvestigacion = idInvestigacion;
    }


    @Column(name="IdInvestigador", nullable=false, length=10)
    public String getIdInvestigador() {
        return this.idInvestigador;
    }
    
    public void setIdInvestigador(String idInvestigador) {
        this.idInvestigador = idInvestigador;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvestigacionInvestigadorId) ) return false;
		 InvestigacionInvestigadorId castOther = ( InvestigacionInvestigadorId ) other; 
         
		 return ( (this.getIdInvestigacion()==castOther.getIdInvestigacion()) || ( this.getIdInvestigacion()!=null && castOther.getIdInvestigacion()!=null && this.getIdInvestigacion().equals(castOther.getIdInvestigacion()) ) )
 && ( (this.getIdInvestigador()==castOther.getIdInvestigador()) || ( this.getIdInvestigador()!=null && castOther.getIdInvestigador()!=null && this.getIdInvestigador().equals(castOther.getIdInvestigador()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdInvestigacion() == null ? 0 : this.getIdInvestigacion().hashCode() );
         result = 37 * result + ( getIdInvestigador() == null ? 0 : this.getIdInvestigador().hashCode() );
         return result;
   }   


}


