package com.comiteetica.hibernate.model;
// Generated 03-sep-2017 15:25:44 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notificacion generated by hbm2java
 */
@Entity
@Table(name="Notificacion"
    ,schema="dbo"
    ,catalog="ComiteEtica"
)
public class Notificacion  implements java.io.Serializable {


     private int idNotificacion;
     private String idDocumento;
     private String tablaProcedencia;
     private String datosRelevante;
     private String link1;
     private String link2;
     private Integer estadoNotificacion;
     private String usuario;
     private String usuarioIngresa;
     private Date fechaIngreso;
     private String usuarioModifica;
     private Date fechaModificacion;

    public Notificacion() {
    }

	
    public Notificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Notificacion(int idNotificacion, String idDocumento, String tablaProcedencia, String datosRelevante, String link1, String link2, Integer estadoNotificacion, String usuario, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion) {
       this.idNotificacion = idNotificacion;
       this.idDocumento = idDocumento;
       this.tablaProcedencia = tablaProcedencia;
       this.datosRelevante = datosRelevante;
       this.link1 = link1;
       this.link2 = link2;
       this.estadoNotificacion = estadoNotificacion;
       this.usuario = usuario;
       this.usuarioIngresa = usuarioIngresa;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModifica = usuarioModifica;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="IdNotificacion", unique=true, nullable=false)
    public int getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }

    
    @Column(name="IdDocumento", length=10)
    public String getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(String idDocumento) {
        this.idDocumento = idDocumento;
    }

    
    @Column(name="TablaProcedencia", length=50)
    public String getTablaProcedencia() {
        return this.tablaProcedencia;
    }
    
    public void setTablaProcedencia(String tablaProcedencia) {
        this.tablaProcedencia = tablaProcedencia;
    }

    
    @Column(name="DatosRelevante", length=100)
    public String getDatosRelevante() {
        return this.datosRelevante;
    }
    
    public void setDatosRelevante(String datosRelevante) {
        this.datosRelevante = datosRelevante;
    }

    
    @Column(name="Link1")
    public String getLink1() {
        return this.link1;
    }
    
    public void setLink1(String link1) {
        this.link1 = link1;
    }

    
    @Column(name="Link2")
    public String getLink2() {
        return this.link2;
    }
    
    public void setLink2(String link2) {
        this.link2 = link2;
    }

    
    @Column(name="EstadoNotificacion")
    public Integer getEstadoNotificacion() {
        return this.estadoNotificacion;
    }
    
    public void setEstadoNotificacion(Integer estadoNotificacion) {
        this.estadoNotificacion = estadoNotificacion;
    }

    
    @Column(name="Usuario", length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="UsuarioIngresa", length=50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }
    
    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaIngreso", length=23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="UsuarioModifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaModificacion", length=23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


