package com.comiteetica.hibernate.model;
// Generated 11-ago-2017 18:56:32 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name = "Pago",
        schema = "dbo",
        catalog = "ComiteEtica"
)
public class Pago implements java.io.Serializable {

    private String idPago;
    private BigDecimal costo;
    private String nroFactura;
    private String observacion;
    private String paramEstadoPago;
    private Integer contador;
    private String usuarioIngresa;
    private Date fechaIngreso;
    private String usuarioModifica;
    private Date fechaModificacion;
    private Set<PagoDetalle> pagoDetalles = new HashSet<PagoDetalle>(0);

    public Pago() {
    }

    public Pago(String idPago) {
        this.idPago = idPago;
    }

    public Pago(String idPago, BigDecimal costo, String nroFactura, String observacion, String paramEstadoPago, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion, Set<PagoDetalle> pagoDetalles) {
        this.idPago = idPago;
        this.costo = costo;
        this.nroFactura = nroFactura;
        this.observacion = observacion;
        this.paramEstadoPago = paramEstadoPago;
        this.usuarioIngresa = usuarioIngresa;
        this.fechaIngreso = fechaIngreso;
        this.usuarioModifica = usuarioModifica;
        this.fechaModificacion = fechaModificacion;
        this.pagoDetalles = pagoDetalles;
    }

    @Id

    @Column(name = "IdPago", nullable = false, length = 10)
    public String getIdPago() {
        return this.idPago;
    }

    public void setIdPago(String idPago) {
        this.idPago = idPago;
    }

    @Column(name = "Costo", precision = 9)
    public BigDecimal getCosto() {
        return this.costo;
    }

    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    @Column(name = "NroFactura", length = 20)
    public String getNroFactura() {
        return this.nroFactura;
    }

    public void setNroFactura(String nroFactura) {
        this.nroFactura = nroFactura;
    }

    @Column(name = "Observacion", length = 150)
    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    @Column(name = "ParamEstadoPago", length = 4)
    public String getParamEstadoPago() {
        return this.paramEstadoPago;
    }

    public void setParamEstadoPago(String paramEstadoPago) {
        this.paramEstadoPago = paramEstadoPago;
    }

    @Column(name = "UsuarioIngresa", length = 50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }

    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaIngreso", length = 23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    @Column(name = "UsuarioModifica", length = 50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaModificacion", length = 23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pago")
    public Set<PagoDetalle> getPagoDetalles() {
        return this.pagoDetalles;
    }

    public void setPagoDetalles(Set<PagoDetalle> pagoDetalles) {
        this.pagoDetalles = pagoDetalles;
    }

    @Column(name = "Contador")
    public Integer getContador() {
        return this.contador;
    }

    public void setContador(Integer contador) {
        this.contador = contador;
    }

}
