package com.comiteetica.hibernate.model;
// Generated 04-ago-2017 18:25:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagoDetalleId generated by hbm2java
 */
@Embeddable
public class PagoDetalleId  implements java.io.Serializable {


     private String idPago;
     private int idPagoDetalle;

    public PagoDetalleId() {
    }

    public PagoDetalleId(String idPago, int idPagoDetalle) {
       this.idPago = idPago;
       this.idPagoDetalle = idPagoDetalle;
    }
   


    @Column(name="IdPago", nullable=false, length=10)
    public String getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(String idPago) {
        this.idPago = idPago;
    }


    @Column(name="IdPagoDetalle", nullable=false)
    public int getIdPagoDetalle() {
        return this.idPagoDetalle;
    }
    
    public void setIdPagoDetalle(int idPagoDetalle) {
        this.idPagoDetalle = idPagoDetalle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagoDetalleId) ) return false;
		 PagoDetalleId castOther = ( PagoDetalleId ) other; 
         
		 return ( (this.getIdPago()==castOther.getIdPago()) || ( this.getIdPago()!=null && castOther.getIdPago()!=null && this.getIdPago().equals(castOther.getIdPago()) ) )
 && (this.getIdPagoDetalle()==castOther.getIdPagoDetalle());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPago() == null ? 0 : this.getIdPago().hashCode() );
         result = 37 * result + this.getIdPagoDetalle();
         return result;
   }   


}


