package com.comiteetica.hibernate.model;
// Generated 11-ago-2017 18:56:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagoDetalleId generated by hbm2java
 */
@Embeddable
public class PagoDetalleId  implements java.io.Serializable {


     private String idPago;
     private int idPagoDetalle;

    public PagoDetalleId() {
    }

    public PagoDetalleId(String idPago, int idPagoDetalle) {
       this.idPago = idPago;
       this.idPagoDetalle = idPagoDetalle;
    }
   


    @Column(name="IdPago", nullable=false, length=10)
    public String getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(String idPago) {
        this.idPago = idPago;
    }


    @Column(name="IdPagoDetalle", nullable=false)
    public int getIdPagoDetalle() {
        return this.idPagoDetalle;
    }
    
    public void setIdPagoDetalle(int idPagoDetalle) {
        this.idPagoDetalle = idPagoDetalle;
    }




}


