package com.comiteetica.hibernate.model;
// Generated 04-ago-2017 18:25:51 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagoDetalle generated by hbm2java
 */
@Entity
@Table(name = "PagoDetalle",
         schema = "dbo",
         catalog = "ComiteEtica"
)
public class PagoDetalle implements java.io.Serializable {

    private PagoDetalleId id;
    private Pago pago;
    private String idCorrespondencia;
    private Integer idCorrespondenciaServicio;
    private String paramTipoServicio;
    private BigDecimal costo;
    private String observacion;
    private String usuarioIngresa;
    private Date fechaIngreso;
    private String usuarioModifica;
    private Date fechaModificacion;

    public PagoDetalle() {
    }

    public PagoDetalle(PagoDetalleId id, Pago pago) {
        this.id = id;
        this.pago = pago;
    }

    public PagoDetalle(PagoDetalleId id, Pago pago, String idCorrespondencia, Integer idCorrespondenciaServicio, String paramTipoServicio, BigDecimal costo, String observacion, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion) {
        this.id = id;
        this.pago = pago;
        this.idCorrespondencia = idCorrespondencia;
        this.idCorrespondenciaServicio = idCorrespondenciaServicio;
        this.paramTipoServicio = paramTipoServicio;
        this.costo = costo;
        this.observacion = observacion;
        this.usuarioIngresa = usuarioIngresa;
        this.fechaIngreso = fechaIngreso;
        this.usuarioModifica = usuarioModifica;
        this.fechaModificacion = fechaModificacion;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idPago", column = @Column(name = "IdPago", nullable = false, length = 10))
        , 
        @AttributeOverride(name = "idPagoDetalle", column = @Column(name = "IdPagoDetalle", nullable = false))})
    public PagoDetalleId getId() {
        return this.id;
    }

    public void setId(PagoDetalleId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdPago", nullable = false, insertable = false, updatable = false)
    public Pago getPago() {
        return this.pago;
    }

    public void setPago(Pago pago) {
        this.pago = pago;
    }

    @Column(name = "IdCorrespondencia", length = 10)
    public String getIdCorrespondencia() {
        return this.idCorrespondencia;
    }

    public void setIdCorrespondencia(String idCorrespondencia) {
        this.idCorrespondencia = idCorrespondencia;
    }

    @Column(name = "IdCorrespondenciaServicio")
    public Integer getIdCorrespondenciaServicio() {
        return this.idCorrespondenciaServicio;
    }

    public void setIdCorrespondenciaServicio(Integer idCorrespondenciaServicio) {
        this.idCorrespondenciaServicio = idCorrespondenciaServicio;
    }

    @Column(name = "ParamTipoServicio", length = 4)
    public String getParamTipoServicio() {
        return this.paramTipoServicio;
    }

    public void setParamTipoServicio(String paramTipoServicio) {
        this.paramTipoServicio = paramTipoServicio;
    }

    @Column(name = "Costo", precision = 9)
    public BigDecimal getCosto() {
        return this.costo;
    }

    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    @Column(name = "Observacion", length = 150)
    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    @Column(name = "UsuarioIngresa", length = 50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }

    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaIngreso", length = 23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    @Column(name = "UsuarioModifica", length = 50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FechaModificacion", length = 23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

}
