package com.comiteetica.hibernate.model;
// Generated 17-jun-2017 14:55:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name="Parametro"
    ,schema="dbo"
    ,catalog="ComiteEtica"
)
public class Parametro  implements java.io.Serializable {


     private String idParametro;
     private String descripcion;
     private String usuarioIngresa;
     private Date fechaIngreso;
     private String usuarioModifica;
     private Date fechaModificacion;
     private Set<ParametroDetalle> parametroDetalles = new HashSet<ParametroDetalle>(0);

    public Parametro() {
    }

	
    public Parametro(String idParametro) {
        this.idParametro = idParametro;
    }
    public Parametro(String idParametro, String descripcion, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion, Set<ParametroDetalle> parametroDetalles) {
       this.idParametro = idParametro;
       this.descripcion = descripcion;
       this.usuarioIngresa = usuarioIngresa;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModifica = usuarioModifica;
       this.fechaModificacion = fechaModificacion;
       this.parametroDetalles = parametroDetalles;
    }
   
     @Id 

    
    @Column(name="IdParametro", nullable=false, length=4)
    public String getIdParametro() {
        return this.idParametro;
    }
    
    public void setIdParametro(String idParametro) {
        this.idParametro = idParametro;
    }

    
    @Column(name="Descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="UsuarioIngresa", length=50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }
    
    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaIngreso", length=23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="UsuarioModifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaModificacion", length=23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="parametro")
    public Set<ParametroDetalle> getParametroDetalles() {
        return this.parametroDetalles;
    }
    
    public void setParametroDetalles(Set<ParametroDetalle> parametroDetalles) {
        this.parametroDetalles = parametroDetalles;
    }




}


