package com.comiteetica.hibernate.model;
// Generated 09-ago-2017 12:35:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParametroDetalleId generated by hbm2java
 */
@Embeddable
public class ParametroDetalleId  implements java.io.Serializable {


     private String idParametro;
     private String idParametroDetalle;

    public ParametroDetalleId() {
    }

    public ParametroDetalleId(String idParametro, String idParametroDetalle) {
       this.idParametro = idParametro;
       this.idParametroDetalle = idParametroDetalle;
    }
   


    @Column(name="IdParametro", nullable=false, length=4)
    public String getIdParametro() {
        return this.idParametro;
    }
    
    public void setIdParametro(String idParametro) {
        this.idParametro = idParametro;
    }


    @Column(name="IdParametroDetalle", nullable=false, length=4)
    public String getIdParametroDetalle() {
        return this.idParametroDetalle;
    }
    
    public void setIdParametroDetalle(String idParametroDetalle) {
        this.idParametroDetalle = idParametroDetalle;
    }




}


