package com.comiteetica.hibernate.model;
// Generated 16/06/2017 12:59:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParametroDetalleId generated by hbm2java
 */
@Embeddable
public class ParametroDetalleId  implements java.io.Serializable {


     private String idParametro;
     private String idParametroDetalle;

    public ParametroDetalleId() {
    }

    public ParametroDetalleId(String idParametro, String idParametroDetalle) {
       this.idParametro = idParametro;
       this.idParametroDetalle = idParametroDetalle;
    }
   


    @Column(name="IdParametro", nullable=false, length=4)
    public String getIdParametro() {
        return this.idParametro;
    }
    
    public void setIdParametro(String idParametro) {
        this.idParametro = idParametro;
    }


    @Column(name="IdParametroDetalle", nullable=false, length=4)
    public String getIdParametroDetalle() {
        return this.idParametroDetalle;
    }
    
    public void setIdParametroDetalle(String idParametroDetalle) {
        this.idParametroDetalle = idParametroDetalle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParametroDetalleId) ) return false;
		 ParametroDetalleId castOther = ( ParametroDetalleId ) other; 
         
		 return ( (this.getIdParametro()==castOther.getIdParametro()) || ( this.getIdParametro()!=null && castOther.getIdParametro()!=null && this.getIdParametro().equals(castOther.getIdParametro()) ) )
 && ( (this.getIdParametroDetalle()==castOther.getIdParametroDetalle()) || ( this.getIdParametroDetalle()!=null && castOther.getIdParametroDetalle()!=null && this.getIdParametroDetalle().equals(castOther.getIdParametroDetalle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdParametro() == null ? 0 : this.getIdParametro().hashCode() );
         result = 37 * result + ( getIdParametroDetalle() == null ? 0 : this.getIdParametroDetalle().hashCode() );
         return result;
   }   


}


