package com.comiteetica.hibernate.model;
// Generated 05-jul-2017 13:55:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatrocinadorCroId generated by hbm2java
 */
@Embeddable
public class PatrocinadorCroId  implements java.io.Serializable {


     private String idPatrocinador;
     private String idCro;

    public PatrocinadorCroId() {
    }

    public PatrocinadorCroId(String idPatrocinador, String idCro) {
       this.idPatrocinador = idPatrocinador;
       this.idCro = idCro;
    }
   


    @Column(name="IdPatrocinador", nullable=false, length=10)
    public String getIdPatrocinador() {
        return this.idPatrocinador;
    }
    
    public void setIdPatrocinador(String idPatrocinador) {
        this.idPatrocinador = idPatrocinador;
    }


    @Column(name="IdCro", nullable=false, length=10)
    public String getIdCro() {
        return this.idCro;
    }
    
    public void setIdCro(String idCro) {
        this.idCro = idCro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatrocinadorCroId) ) return false;
		 PatrocinadorCroId castOther = ( PatrocinadorCroId ) other; 
         
		 return ( (this.getIdPatrocinador()==castOther.getIdPatrocinador()) || ( this.getIdPatrocinador()!=null && castOther.getIdPatrocinador()!=null && this.getIdPatrocinador().equals(castOther.getIdPatrocinador()) ) )
 && ( (this.getIdCro()==castOther.getIdCro()) || ( this.getIdCro()!=null && castOther.getIdCro()!=null && this.getIdCro().equals(castOther.getIdCro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPatrocinador() == null ? 0 : this.getIdPatrocinador().hashCode() );
         result = 37 * result + ( getIdCro() == null ? 0 : this.getIdCro().hashCode() );
         return result;
   }   


}


