package com.comiteetica.hibernate.model;
// Generated 05-jul-2017 13:55:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProvinciaId generated by hbm2java
 */
@Embeddable
public class ProvinciaId  implements java.io.Serializable {


     private String idDepartamento;
     private String idProvincia;

    public ProvinciaId() {
    }

    public ProvinciaId(String idDepartamento, String idProvincia) {
       this.idDepartamento = idDepartamento;
       this.idProvincia = idProvincia;
    }
   


    @Column(name="IdDepartamento", nullable=false, length=2)
    public String getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(String idDepartamento) {
        this.idDepartamento = idDepartamento;
    }


    @Column(name="IdProvincia", nullable=false, length=2)
    public String getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(String idProvincia) {
        this.idProvincia = idProvincia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProvinciaId) ) return false;
		 ProvinciaId castOther = ( ProvinciaId ) other; 
         
		 return ( (this.getIdDepartamento()==castOther.getIdDepartamento()) || ( this.getIdDepartamento()!=null && castOther.getIdDepartamento()!=null && this.getIdDepartamento().equals(castOther.getIdDepartamento()) ) )
 && ( (this.getIdProvincia()==castOther.getIdProvincia()) || ( this.getIdProvincia()!=null && castOther.getIdProvincia()!=null && this.getIdProvincia().equals(castOther.getIdProvincia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdDepartamento() == null ? 0 : this.getIdDepartamento().hashCode() );
         result = 37 * result + ( getIdProvincia() == null ? 0 : this.getIdProvincia().hashCode() );
         return result;
   }   


}


