package com.comiteetica.hibernate.model;
// Generated 17-jun-2017 14:55:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegistroBitacoraId generated by hbm2java
 */
@Embeddable
public class RegistroBitacoraId  implements java.io.Serializable {


     private String idRegistro;
     private int idBitacora;

    public RegistroBitacoraId() {
    }

    public RegistroBitacoraId(String idRegistro, int idBitacora) {
       this.idRegistro = idRegistro;
       this.idBitacora = idBitacora;
    }
   


    @Column(name="IdRegistro", nullable=false, length=10)
    public String getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(String idRegistro) {
        this.idRegistro = idRegistro;
    }


    @Column(name="IdBitacora", nullable=false)
    public int getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(int idBitacora) {
        this.idBitacora = idBitacora;
    }




}


