package com.comiteetica.hibernate.model;
// Generated 05-jul-2017 13:55:59 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name="Sede"
    ,schema="dbo"
    ,catalog="ComiteEtica"
)
public class Sede  implements java.io.Serializable {


     private String idSede;
     private String nombre;
     private String direccion;
     private String idDepartamento;
     private String idProvincia;
     private String idDistrito;
     private String usuarioIngresa;
     private Date fechaIngreso;
     private String usuarioModifica;
     private Date fechaModificacion;
     private Set<InvestigacionSede> investigacionSedes = new HashSet<InvestigacionSede>(0);

    public Sede() {
    }

	
    public Sede(String idSede) {
        this.idSede = idSede;
    }
    public Sede(String idSede, String nombre, String direccion, String idDepartamento, String idProvincia, String idDistrito, String usuarioIngresa, Date fechaIngreso, String usuarioModifica, Date fechaModificacion, Set<InvestigacionSede> investigacionSedes) {
       this.idSede = idSede;
       this.nombre = nombre;
       this.direccion = direccion;
       this.idDepartamento = idDepartamento;
       this.idProvincia = idProvincia;
       this.idDistrito = idDistrito;
       this.usuarioIngresa = usuarioIngresa;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModifica = usuarioModifica;
       this.fechaModificacion = fechaModificacion;
       this.investigacionSedes = investigacionSedes;
    }
   
     @Id 

    
    @Column(name="IdSede", unique=true, nullable=false, length=10)
    public String getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(String idSede) {
        this.idSede = idSede;
    }

    
    @Column(name="Nombre", length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Direccion", length=250)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="IdDepartamento", length=2)
    public String getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(String idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="IdProvincia", length=2)
    public String getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(String idProvincia) {
        this.idProvincia = idProvincia;
    }

    
    @Column(name="IdDistrito", length=2)
    public String getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(String idDistrito) {
        this.idDistrito = idDistrito;
    }

    
    @Column(name="UsuarioIngresa", length=50)
    public String getUsuarioIngresa() {
        return this.usuarioIngresa;
    }
    
    public void setUsuarioIngresa(String usuarioIngresa) {
        this.usuarioIngresa = usuarioIngresa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaIngreso", length=23)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="UsuarioModifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaModificacion", length=23)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="sede")
    public Set<InvestigacionSede> getInvestigacionSedes() {
        return this.investigacionSedes;
    }
    
    @JsonIgnore
    public void setInvestigacionSedes(Set<InvestigacionSede> investigacionSedes) {
        this.investigacionSedes = investigacionSedes;
    }




}


