package com.comiteetica.hibernate.model;
// Generated 09-ago-2017 12:35:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SerieCorrelativoId generated by hbm2java
 */
@Embeddable
public class SerieCorrelativoId  implements java.io.Serializable {


     private String idSerie;
     private String idCorrelativo;

    public SerieCorrelativoId() {
    }

    public SerieCorrelativoId(String idSerie, String idCorrelativo) {
       this.idSerie = idSerie;
       this.idCorrelativo = idCorrelativo;
    }
   


    @Column(name="IdSerie", nullable=false, length=3)
    public String getIdSerie() {
        return this.idSerie;
    }
    
    public void setIdSerie(String idSerie) {
        this.idSerie = idSerie;
    }


    @Column(name="IdCorrelativo", nullable=false, length=7)
    public String getIdCorrelativo() {
        return this.idCorrelativo;
    }
    
    public void setIdCorrelativo(String idCorrelativo) {
        this.idCorrelativo = idCorrelativo;
    }




}


