package com.comiteetica.hibernate.model;
// Generated 04-ago-2017 18:25:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SerieCorrelativoId generated by hbm2java
 */
@Embeddable
public class SerieCorrelativoId  implements java.io.Serializable {


     private String idSerie;
     private String idCorrelativo;

    public SerieCorrelativoId() {
    }

    public SerieCorrelativoId(String idSerie, String idCorrelativo) {
       this.idSerie = idSerie;
       this.idCorrelativo = idCorrelativo;
    }
   


    @Column(name="IdSerie", nullable=false, length=3)
    public String getIdSerie() {
        return this.idSerie;
    }
    
    public void setIdSerie(String idSerie) {
        this.idSerie = idSerie;
    }


    @Column(name="IdCorrelativo", nullable=false, length=7)
    public String getIdCorrelativo() {
        return this.idCorrelativo;
    }
    
    public void setIdCorrelativo(String idCorrelativo) {
        this.idCorrelativo = idCorrelativo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SerieCorrelativoId) ) return false;
		 SerieCorrelativoId castOther = ( SerieCorrelativoId ) other; 
         
		 return ( (this.getIdSerie()==castOther.getIdSerie()) || ( this.getIdSerie()!=null && castOther.getIdSerie()!=null && this.getIdSerie().equals(castOther.getIdSerie()) ) )
 && ( (this.getIdCorrelativo()==castOther.getIdCorrelativo()) || ( this.getIdCorrelativo()!=null && castOther.getIdCorrelativo()!=null && this.getIdCorrelativo().equals(castOther.getIdCorrelativo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdSerie() == null ? 0 : this.getIdSerie().hashCode() );
         result = 37 * result + ( getIdCorrelativo() == null ? 0 : this.getIdCorrelativo().hashCode() );
         return result;
   }   


}


